apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cassandra-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/cassandra-data