apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cassandra-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi