apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-cassandra
  namespace: default
spec:
  serviceName: svc-cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest
        ports:
        - containerPort: 9042
          name: cql
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "CassandraCluster"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
      volumes:
      - name: config
        configMap:
          name: cm-kube-root-ca.crt
      - name: secret
        secret:
          secretName: sa-default
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi 