apiVersion: v1
kind: Service
metadata:
  name: svc-cassandra
  namespace: default
spec:
  type: NodePort
  selector:
    app: cassandra
  ports:
  - port: 9042
    targetPort: 9042
    nodePort: 30042 
    protocol: TCP
    name: cql